### ISSUE TITLE
Request to add support for the case of unaligned number of rows for BrgemmTPP leveraging VNNI layout

### ISSUE THREAD

**Issue by CaoE** [libxsmm/tpp-pytorch-extension#5]
`unaligned number of rows` is not supported by `XformExtTPP` https://github.com/libxsmm/tpp-pytorch-extension/blob/d4c6a32228349e96b7bb32acf3b68c9d49887e82/src/csrc/xsmm_functors.h#L1704 which prevents `BrgemmTPP ` from utilizing VNNI layout to achieve better performance, and thus prevents the transformer models from achieving better performance for flash attention. 
Can VNNI layout reorder be integrated into `BrgemmTPP ` and support such “unaligned number of rows” case ?

**Comment by ddkalamk** [comment]
`XfromExtTPP` supports padding when input is unaligned to VNNI pack size. However, there needs enough space in the output buffer to store padded output hence `out_rows` should be padded size.

**Comment by CaoE** [comment]
@ddkalamk Can VNNI layout reorder be integrated into `BrgemmTPP` so the padding and reorder can be done inside `BrgemmTPP`

**Comment by CaoE** [comment]
> `XfromExtTPP` supports padding when input is unaligned to VNNI pack size. However, there needs enough space in the output buffer to store padded output hence `out_rows` should be padded size.

Cloud you please share me an example for using  padding of `XfromExtTPP` ? Thank you.
